### ISSUE TITLE
Undefined GNSS ID when decoding HAS messages

### ISSUE THREAD

**Issue by Vkerker** [yoronneko/qzsl6tool#39] opened 2024-05-02 14:09 UTC
Dear Satoshi. Thank you for this amazing project.
Currently I encounter an issue when running gale6read.py. After running septread.py to extract Gallileo HAS messages, I run gale6read and at some point it encounters GNSS with id other than 0-5 and returns error. The reciever is Septentrio Mosaic X5, firmware version 4.14.4. This problem occurs from time to time, not with every file.
Thank you for your time.

**Comment by yoronneko** [comment] 2024-05-05 23:53
Dear Vkerker,

Thank you very much for your report.

I have tried to decode HAS messages from May 1st 2024 to May 5th with [my HAS archive data](https://phys.info.hiroshima-cu.ac.jp/gnss/has/) and the latest gale6read.py, and I didn't encounter decode error (the data is not Septentrio receiver output but NovAtel receiver output, however).

In fact, the gale6read.py has [omitted CRC test](https://github.com/yoronneko/qzsl6tool/blob/96879c4693485243588b26a3c591f6ad70931375/python/gale6read.py#L319C1-L319C57), and the GNSS ID errors would be source of the residual errors due to the Viterbi decoder's error correction.

Please be patient to add the CRC test code to gale6read.py.

**Comment by yoronneko** [comment] 2024-05-06 01:43
I remembered I omitted the CRC test because NovAtel receivers did not output neither CRC parity and tail bits for Galileo E6-B raw data.

There may be two ways for resolving this issue; (1) addition of CRC calculation to novread.py and addition of CRC check to gale6read.py, or (2) addition of CRC check to septread.py.

Please give me time to chose the way and fix the issue.

**Comment by yoronneko** [comment] 2024-07-23 01:19
I confirmed this error was caused due to CNAV messages that include CRC errors. I updated septread.py to reject erroneous CNAV messages. Ihope this modification resolves the issue.

**Closed** 2024-07-23 01:23 UTC
Labels: bug
